# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/stuts/PersonalCode/ece385/final_project/final_project.srcs/sources_1/ip/car_rom_1/car_rom.xci
# IP: The module: 'car_rom' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/stuts/PersonalCode/ece385/final_project/final_project.gen/sources_1/ip/car_rom_2/car_rom_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'car_rom'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: C:/Users/stuts/PersonalCode/ece385/final_project/final_project.srcs/sources_1/ip/car_rom_1/car_rom.xci
# IP: The module: 'car_rom' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/stuts/PersonalCode/ece385/final_project/final_project.gen/sources_1/ip/car_rom_2/car_rom_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'car_rom'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
