# 
# Report generation script generated by Vivado
# 

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
namespace eval ::optrace {
  variable script "C:/Users/stuts/PersonalCode/ece385/final_project/final_project.runs/impl_1/zoom_top.tcl"
  variable category "vivado_impl"
}

# Try to connect to running dispatch if we haven't done so already.
# This code assumes that the Tcl interpreter is not using threads,
# since the ::dispatch::connected variable isn't mutex protected.
if {![info exists ::dispatch::connected]} {
  namespace eval ::dispatch {
    variable connected false
    if {[llength [array get env XILINX_CD_CONNECT_ID]] > 0} {
      set result "true"
      if {[catch {
        if {[lsearch -exact [package names] DispatchTcl] < 0} {
          set result [load librdi_cd_clienttcl[info sharedlibextension]] 
        }
        if {$result eq "false"} {
          puts "WARNING: Could not load dispatch client library"
        }
        set connect_id [ ::dispatch::init_client -mode EXISTING_SERVER ]
        if { $connect_id eq "" } {
          puts "WARNING: Could not initialize dispatch client"
        } else {
          puts "INFO: Dispatch client connection id - $connect_id"
          set connected true
        }
      } catch_res]} {
        puts "WARNING: failed to connect to dispatch server - $catch_res"
      }
    }
  }
}
if {$::dispatch::connected} {
  # Remove the dummy proc if it exists.
  if { [expr {[llength [info procs ::OPTRACE]] > 0}] } {
    rename ::OPTRACE ""
  }
  proc ::OPTRACE { task action {tags {} } } {
    ::vitis_log::op_trace "$task" $action -tags $tags -script $::optrace::script -category $::optrace::category
  }
  # dispatch is generic. We specifically want to attach logging.
  ::vitis_log::connect_client
} else {
  # Add dummy proc if it doesn't exist.
  if { [expr {[llength [info procs ::OPTRACE]] == 0}] } {
    proc ::OPTRACE {{arg1 \"\" } {arg2 \"\"} {arg3 \"\" } {arg4 \"\"} {arg5 \"\" } {arg6 \"\"}} {
        # Do nothing
    }
  }
}

proc start_step { step } {
  set stopFile ".stop.rst"
  if {[file isfile .stop.rst]} {
    puts ""
    puts "*** Halting run - EA reset detected ***"
    puts ""
    puts ""
    return -code error
  }
  set beginFile ".$step.begin.rst"
  set platform "$::tcl_platform(platform)"
  set user "$::tcl_platform(user)"
  set pid [pid]
  set host ""
  if { [string equal $platform unix] } {
    if { [info exist ::env(HOSTNAME)] } {
      set host $::env(HOSTNAME)
    } elseif { [info exist ::env(HOST)] } {
      set host $::env(HOST)
    }
  } else {
    if { [info exist ::env(COMPUTERNAME)] } {
      set host $::env(COMPUTERNAME)
    }
  }
  set ch [open $beginFile w]
  puts $ch "<?xml version=\"1.0\"?>"
  puts $ch "<ProcessHandle Version=\"1\" Minor=\"0\">"
  puts $ch "    <Process Command=\".planAhead.\" Owner=\"$user\" Host=\"$host\" Pid=\"$pid\">"
  puts $ch "    </Process>"
  puts $ch "</ProcessHandle>"
  close $ch
}

proc end_step { step } {
  set endFile ".$step.end.rst"
  set ch [open $endFile w]
  close $ch
}

proc step_failed { step } {
  set endFile ".$step.error.rst"
  set ch [open $endFile w]
  close $ch
OPTRACE "impl_1" END { }
}


OPTRACE "impl_1" START { ROLLUP_1 }
OPTRACE "Phase: Init Design" START { ROLLUP_AUTO }
start_step init_design
set ACTIVE_STEP init_design
set rc [catch {
  create_msg_db init_design.pb
  set_param chipscope.maxJobs 2
OPTRACE "create in-memory project" START { }
  create_project -in_memory -part xc7s50csga324-1
  set_property design_mode GateLvl [current_fileset]
  set_param project.singleFileAddWarning.threshold 0
OPTRACE "create in-memory project" END { }
OPTRACE "set parameters" START { }
  set_property webtalk.parent_dir C:/Users/stuts/PersonalCode/ece385/final_project/final_project.cache/wt [current_project]
  set_property parent.project_path C:/Users/stuts/PersonalCode/ece385/final_project/final_project.xpr [current_project]
  set_property ip_repo_paths C:/Users/stuts/PersonalCode/ece385/ip_repo [current_project]
  update_ip_catalog
  set_property ip_output_repo C:/Users/stuts/PersonalCode/ece385/final_project/final_project.cache/ip [current_project]
  set_property ip_cache_permissions {read write} [current_project]
  set_property XPM_LIBRARIES {XPM_CDC XPM_FIFO XPM_MEMORY} [current_project]
OPTRACE "set parameters" END { }
OPTRACE "add files" START { }
  add_files -quiet C:/Users/stuts/PersonalCode/ece385/final_project/final_project.runs/synth_1/zoom_top.dcp
  set_msg_config -source 4 -id {BD 41-1661} -limit 0
  set_param project.isImplRun true
  read_ip -quiet C:/Users/stuts/PersonalCode/ece385/final_project/final_project.srcs/sources_1/ip/tree_rom_2/tree_rom.xci
  add_files C:/Users/stuts/PersonalCode/ece385/final_project/final_project.srcs/sources_1/bd/mb_zoom/mb_zoom.bd
  read_ip -quiet C:/Users/stuts/PersonalCode/ece385/final_project/final_project.srcs/sources_1/ip/hdmi_tx_0/hdmi_tx_0.xci
  read_ip -quiet C:/Users/stuts/PersonalCode/ece385/final_project/final_project.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xci
  read_ip -quiet C:/Users/stuts/PersonalCode/ece385/final_project/final_project.srcs/sources_1/ip/city_backdrop_rom/city_backdrop_rom.xci
  read_ip -quiet C:/Users/stuts/PersonalCode/ece385/final_project/final_project.srcs/sources_1/ip/trashcan_rom/trashcan_rom.xci
  read_ip -quiet C:/Users/stuts/PersonalCode/ece385/final_project/final_project.srcs/sources_1/ip/puddle_rom/puddle_rom.xci
  read_ip -quiet C:/Users/stuts/PersonalCode/ece385/final_project/final_project.srcs/sources_1/ip/cone_rom/cone_rom.xci
  read_ip -quiet C:/Users/stuts/PersonalCode/ece385/final_project/final_project.srcs/sources_1/ip/main_menu_rom/main_menu_rom.xci
  read_ip -quiet C:/Users/stuts/PersonalCode/ece385/final_project/final_project.srcs/sources_1/ip/game_over_rom/game_over_rom.xci
  read_ip -quiet C:/Users/stuts/PersonalCode/ece385/final_project/final_project.srcs/sources_1/ip/numbers_rom/numbers_rom.xci
  read_ip -quiet C:/Users/stuts/PersonalCode/ece385/final_project/final_project.srcs/sources_1/ip/score_rom/score_rom.xci
  read_ip -quiet C:/Users/stuts/PersonalCode/ece385/final_project/final_project.srcs/sources_1/ip/time_rom/time_rom.xci
  read_ip -quiet C:/Users/stuts/PersonalCode/ece385/final_project/final_project.srcs/sources_1/ip/instructions_rom/instructions_rom.xci
  read_ip -quiet C:/Users/stuts/PersonalCode/ece385/final_project/final_project.srcs/sources_1/ip/car_rom_1/car_rom.xci
  read_ip -quiet C:/Users/stuts/PersonalCode/ece385/final_project/final_project.srcs/sources_1/ip/barricade_rom/barricade_rom.xci
  read_ip -quiet C:/Users/stuts/PersonalCode/ece385/final_project/final_project.srcs/sources_1/ip/blue_car_rom/blue_car_rom.xci
  read_ip -quiet C:/Users/stuts/PersonalCode/ece385/final_project/final_project.srcs/sources_1/ip/green_car_rom/green_car_rom.xci
  read_ip -quiet C:/Users/stuts/PersonalCode/ece385/final_project/final_project.srcs/sources_1/ip/purple_car_rom/purple_car_rom.xci
  read_ip -quiet C:/Users/stuts/PersonalCode/ece385/final_project/final_project.srcs/sources_1/ip/yellow_car_rom/yellow_car_rom.xci
  read_ip -quiet C:/Users/stuts/PersonalCode/ece385/final_project/final_project.srcs/sources_1/ip/explosion1_rom/explosion1_rom.xci
  read_ip -quiet C:/Users/stuts/PersonalCode/ece385/final_project/final_project.srcs/sources_1/ip/explosion2_rom/explosion2_rom.xci
  read_ip -quiet C:/Users/stuts/PersonalCode/ece385/final_project/final_project.srcs/sources_1/ip/explosion3_rom/explosion3_rom.xci
  read_ip -quiet C:/Users/stuts/PersonalCode/ece385/final_project/final_project.srcs/sources_1/ip/explosion4_rom/explosion4_rom.xci
  read_ip -quiet C:/Users/stuts/PersonalCode/ece385/final_project/final_project.srcs/sources_1/ip/explosion5_rom/explosion5_rom.xci
  read_ip -quiet C:/Users/stuts/PersonalCode/ece385/final_project/final_project.srcs/sources_1/ip/explosion6_rom/explosion6_rom.xci
  read_ip -quiet C:/Users/stuts/PersonalCode/ece385/final_project/final_project.srcs/sources_1/ip/explosion7_rom/explosion7_rom.xci
  read_ip -quiet C:/Users/stuts/PersonalCode/ece385/final_project/final_project.srcs/sources_1/ip/explosion8_rom/explosion8_rom.xci
  read_ip -quiet C:/Users/stuts/PersonalCode/ece385/final_project/final_project.srcs/sources_1/ip/explosion9_rom/explosion9_rom.xci
  read_ip -quiet C:/Users/stuts/PersonalCode/ece385/final_project/final_project.srcs/sources_1/ip/explosion10_rom/explosion10_rom.xci
  read_ip -quiet C:/Users/stuts/PersonalCode/ece385/final_project/final_project.srcs/sources_1/ip/desert_background_rom/desert_background_rom.xci
  read_ip -quiet C:/Users/stuts/PersonalCode/ece385/final_project/final_project.srcs/sources_1/ip/satellite_rom/satellite_rom.xci
  read_ip -quiet C:/Users/stuts/PersonalCode/ece385/final_project/final_project.srcs/sources_1/ip/cactus_rom_1/cactus_rom.xci
  read_ip -quiet C:/Users/stuts/PersonalCode/ece385/final_project/final_project.srcs/sources_1/ip/space_background_rom_2/space_background_rom.xci
  read_ip -quiet C:/Users/stuts/PersonalCode/ece385/final_project/final_project.srcs/sources_1/ip/bgselect_rom/bgselect_rom.xci
  set_param project.isImplRun false
OPTRACE "read constraints: implementation" START { }
  read_xdc C:/Users/stuts/PersonalCode/ece385/final_project/final_project.srcs/constrs_1/imports/pin_assignment/mb_usb_hdmi_top.xdc
OPTRACE "read constraints: implementation" END { }
OPTRACE "add files" END { }
OPTRACE "link_design" START { }
  set_param project.isImplRun true
  link_design -top zoom_top -part xc7s50csga324-1 
OPTRACE "link_design" END { }
  set_param project.isImplRun false
OPTRACE "gray box cells" START { }
OPTRACE "gray box cells" END { }
OPTRACE "init_design_reports" START { REPORT }
OPTRACE "init_design_reports" END { }
OPTRACE "init_design_write_hwdef" START { }
OPTRACE "init_design_write_hwdef" END { }
  close_msg_db -file init_design.pb
} RESULT]
if {$rc} {
  step_failed init_design
  return -code error $RESULT
} else {
  end_step init_design
  unset ACTIVE_STEP 
}

OPTRACE "Phase: Init Design" END { }
OPTRACE "Phase: Opt Design" START { ROLLUP_AUTO }
start_step opt_design
set ACTIVE_STEP opt_design
set rc [catch {
  create_msg_db opt_design.pb
OPTRACE "read constraints: opt_design" START { }
OPTRACE "read constraints: opt_design" END { }
OPTRACE "opt_design" START { }
  opt_design 
OPTRACE "opt_design" END { }
OPTRACE "read constraints: opt_design_post" START { }
OPTRACE "read constraints: opt_design_post" END { }
OPTRACE "Opt Design: write_checkpoint" START { CHECKPOINT }
  write_checkpoint -force zoom_top_opt.dcp
OPTRACE "Opt Design: write_checkpoint" END { }
OPTRACE "opt_design reports" START { REPORT }
  create_report "impl_1_opt_report_drc_0" "report_drc -file zoom_top_drc_opted.rpt -pb zoom_top_drc_opted.pb -rpx zoom_top_drc_opted.rpx"
OPTRACE "opt_design reports" END { }
  close_msg_db -file opt_design.pb
} RESULT]
if {$rc} {
  step_failed opt_design
  return -code error $RESULT
} else {
  end_step opt_design
  unset ACTIVE_STEP 
}

OPTRACE "Phase: Opt Design" END { }
OPTRACE "Phase: Place Design" START { ROLLUP_AUTO }
start_step place_design
set ACTIVE_STEP place_design
set rc [catch {
  create_msg_db place_design.pb
OPTRACE "read constraints: place_design" START { }
OPTRACE "read constraints: place_design" END { }
  if { [llength [get_debug_cores -quiet] ] > 0 }  { 
OPTRACE "implement_debug_core" START { }
    implement_debug_core 
OPTRACE "implement_debug_core" END { }
  } 
OPTRACE "place_design" START { }
  place_design 
OPTRACE "place_design" END { }
OPTRACE "read constraints: place_design_post" START { }
OPTRACE "read constraints: place_design_post" END { }
OPTRACE "Place Design: write_checkpoint" START { CHECKPOINT }
  write_checkpoint -force zoom_top_placed.dcp
OPTRACE "Place Design: write_checkpoint" END { }
OPTRACE "place_design reports" START { REPORT }
  create_report "impl_1_place_report_io_0" "report_io -file zoom_top_io_placed.rpt"
  create_report "impl_1_place_report_utilization_0" "report_utilization -file zoom_top_utilization_placed.rpt -pb zoom_top_utilization_placed.pb"
  create_report "impl_1_place_report_control_sets_0" "report_control_sets -verbose -file zoom_top_control_sets_placed.rpt"
OPTRACE "place_design reports" END { }
  close_msg_db -file place_design.pb
} RESULT]
if {$rc} {
  step_failed place_design
  return -code error $RESULT
} else {
  end_step place_design
  unset ACTIVE_STEP 
}

OPTRACE "Phase: Place Design" END { }
OPTRACE "Phase: Physical Opt Design" START { ROLLUP_AUTO }
start_step phys_opt_design
set ACTIVE_STEP phys_opt_design
set rc [catch {
  create_msg_db phys_opt_design.pb
OPTRACE "read constraints: phys_opt_design" START { }
OPTRACE "read constraints: phys_opt_design" END { }
OPTRACE "phys_opt_design" START { }
  phys_opt_design 
OPTRACE "phys_opt_design" END { }
OPTRACE "read constraints: phys_opt_design_post" START { }
OPTRACE "read constraints: phys_opt_design_post" END { }
OPTRACE "Post-Place Phys Opt Design: write_checkpoint" START { CHECKPOINT }
  write_checkpoint -force zoom_top_physopt.dcp
OPTRACE "Post-Place Phys Opt Design: write_checkpoint" END { }
OPTRACE "phys_opt_design report" START { REPORT }
OPTRACE "phys_opt_design report" END { }
  close_msg_db -file phys_opt_design.pb
} RESULT]
if {$rc} {
  step_failed phys_opt_design
  return -code error $RESULT
} else {
  end_step phys_opt_design
  unset ACTIVE_STEP 
}

OPTRACE "Phase: Physical Opt Design" END { }
OPTRACE "Phase: Route Design" START { ROLLUP_AUTO }
start_step route_design
set ACTIVE_STEP route_design
set rc [catch {
  create_msg_db route_design.pb
OPTRACE "read constraints: route_design" START { }
OPTRACE "read constraints: route_design" END { }
OPTRACE "route_design" START { }
  route_design 
OPTRACE "route_design" END { }
OPTRACE "read constraints: route_design_post" START { }
OPTRACE "read constraints: route_design_post" END { }
OPTRACE "Route Design: write_checkpoint" START { CHECKPOINT }
  write_checkpoint -force zoom_top_routed.dcp
OPTRACE "Route Design: write_checkpoint" END { }
OPTRACE "route_design reports" START { REPORT }
  create_report "impl_1_route_report_drc_0" "report_drc -file zoom_top_drc_routed.rpt -pb zoom_top_drc_routed.pb -rpx zoom_top_drc_routed.rpx"
  create_report "impl_1_route_report_methodology_0" "report_methodology -file zoom_top_methodology_drc_routed.rpt -pb zoom_top_methodology_drc_routed.pb -rpx zoom_top_methodology_drc_routed.rpx"
  create_report "impl_1_route_report_power_0" "report_power -file zoom_top_power_routed.rpt -pb zoom_top_power_summary_routed.pb -rpx zoom_top_power_routed.rpx"
  create_report "impl_1_route_report_route_status_0" "report_route_status -file zoom_top_route_status.rpt -pb zoom_top_route_status.pb"
  create_report "impl_1_route_report_timing_summary_0" "report_timing_summary -max_paths 10 -report_unconstrained -file zoom_top_timing_summary_routed.rpt -pb zoom_top_timing_summary_routed.pb -rpx zoom_top_timing_summary_routed.rpx -warn_on_violation "
  create_report "impl_1_route_report_incremental_reuse_0" "report_incremental_reuse -file zoom_top_incremental_reuse_routed.rpt"
  create_report "impl_1_route_report_clock_utilization_0" "report_clock_utilization -file zoom_top_clock_utilization_routed.rpt"
  create_report "impl_1_route_report_bus_skew_0" "report_bus_skew -warn_on_violation -file zoom_top_bus_skew_routed.rpt -pb zoom_top_bus_skew_routed.pb -rpx zoom_top_bus_skew_routed.rpx"
OPTRACE "route_design reports" END { }
OPTRACE "route_design misc" START { }
  close_msg_db -file route_design.pb
} RESULT]
if {$rc} {
OPTRACE "route_design write_checkpoint" START { CHECKPOINT }
OPTRACE "route_design write_checkpoint" END { }
  write_checkpoint -force zoom_top_routed_error.dcp
  step_failed route_design
  return -code error $RESULT
} else {
  end_step route_design
  unset ACTIVE_STEP 
}

OPTRACE "route_design misc" END { }
OPTRACE "Phase: Route Design" END { }
OPTRACE "impl_1" END { }
